### ISSUE TITLE
User roles are being ignored?

### ISSUE THREAD

**Issue by ValdasK** [authbucket/oauth2-symfony-bundle#4]
Using provided firewall (oauth2_resource), when AccessTokenToken is being created, roles are left as an empty array, therefore in controller, after authentication, `$this->getUser()` returns null. How do I set proper roles for access_token user?

**Comment by hswong3i** [comment]
!? So already solve the issue?

**Comment by ValdasK** [comment]
I did a mistake investigating issue I was having.

What really happens is that created access token has user set as string, not as an object.

Do you have any tips how to set user object into token, not user username as string?
